import * as path from 'node:path';

import { BaseAgentAdapter } from '../shared/base-adapter.js';
import { renderManagedMarkdownDocument } from '../shared/rendering.js';
import type {
  AdapterEnvironment,
  AdapterPlanInput,
  AgentAdapterId,
  SupportLevel,
} from '../shared/types.js';

export class CodexAdapter extends BaseAgentAdapter {
  override readonly id: AgentAdapterId = 'codex';

  protected override readonly adapterSupportLevel: SupportLevel = 'full';

  protected override readonly detectionConfiguration = {
    executables: ['codex'],
    homeDirectories: ['.codex'],
    homeFiles: ['.codex/config.toml'],
    workspaceFiles: ['.codex/config.toml'],
  };

  protected override async buildPrimaryArtifacts(
    input: AdapterPlanInput,
  ): Promise<
    readonly {
      path: string;
      content: string;
      role: 'instructions';
      reason: string;
    }[]
  > {
    return [
      {
        path: path.join(this.workspaceRoot, 'AGENTS.md'),
        content: renderManagedMarkdownDocument({
          adapterId: 'codex',
          role: 'instructions',
          title: 'Org Agent Skills',
          intro:
            'Repository-level Codex instructions generated by Org Agent Skills. Edit the source artifacts instead of editing this file directly.',
          baseGuidance: input.baseGuidance,
          skills: input.skills,
        }),
        role: 'instructions',
        reason:
          'Render always-on guidance into the repository-level AGENTS.md that Codex discovers.',
      },
    ];
  }
}
