import * as path from 'node:path';

import { buildManagedComment } from './managed-state.js';
import type {
  AgentAdapterId,
  GuidanceSection,
  SkillReference,
} from './types.js';

export function renderManagedMarkdownDocument(options: {
  readonly adapterId: AgentAdapterId;
  readonly role: 'instructions' | 'rule';
  readonly title: string;
  readonly intro: string;
  readonly baseGuidance: readonly GuidanceSection[];
  readonly skills: readonly SkillReference[];
}): string {
  const sections: string[] = [
    buildManagedComment(options.adapterId, options.role),
    `# ${options.title}`,
    options.intro.trim(),
  ];

  sections.push(renderBaseGuidance(options.baseGuidance));
  sections.push(renderSkillSection(options.skills));

  return `${sections.filter((section) => section.length > 0).join('\n\n')}\n`;
}

export function renderCursorRuleDocument(options: {
  readonly baseGuidance: readonly GuidanceSection[];
  readonly skills: readonly SkillReference[];
}): string {
  const body = renderManagedMarkdownDocument({
    adapterId: 'cursor',
    role: 'rule',
    title: 'Org Agent Skills',
    intro:
      'Always-on Cursor guidance generated by Org Agent Skills. Edit the org-managed source artifacts instead of this file.',
    baseGuidance: options.baseGuidance,
    skills: options.skills,
  });

  return `---\ndescription: Organization-managed always-on guidance\nalwaysApply: true\n---\n\n${body}`;
}

function renderBaseGuidance(baseGuidance: readonly GuidanceSection[]): string {
  if (baseGuidance.length === 0) {
    return '## Always-On Guidance\n\n_No organization guidance was selected for this workspace._';
  }

  const sections = baseGuidance.map((section) => {
    const normalizedTitle =
      section.title.trim().length > 0 ? section.title.trim() : section.sourceId;
    const normalizedContent = normalizeMarkdownBlock(section.content);
    return `### ${normalizedTitle}\n\n${normalizedContent}\n\n_Source: \`${section.sourceId}\`_`;
  });

  return `## Always-On Guidance\n\n${sections.join('\n\n')}`;
}

function renderSkillSection(skills: readonly SkillReference[]): string {
  if (skills.length === 0) {
    return '## Managed Skills\n\n_No shared skills were selected for this workspace._';
  }

  const lines = skills.map((skill) => {
    const displayName = skill.displayName ?? skill.id;
    const description = skill.description?.trim();
    const sourceLabel = path.basename(skill.sourcePath);
    const detailSuffix =
      description !== undefined && description.length > 0
        ? `: ${description}`
        : '';
    return `- \`${displayName}\` from \`${sourceLabel}\`${detailSuffix}`;
  });

  return `## Managed Skills\n\n${lines.join('\n')}`;
}

function normalizeMarkdownBlock(content: string): string {
  return content
    .trim()
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n');
}
